<?
$sysRoleList = array(
	array("用户管理",
		array(
			new PowerItem('A0','查看全部客户',UserIsInRole('A0',$adminRole)),
			new PowerItem('A1' , '查看个人管理的客户',UserIsInRole('A1',$adminRole)),
			new PowerItem('A01','查看定制网站客户',UserIsInRole('A01',$adminRole)),
			new PowerItem('A02','查看套餐网站客户',UserIsInRole('A02',$adminRole)),
			new POwerItem('A03','查看入门型网站客户',UserIsInRole('A03',$adminRole)),
			new PowerItem('A04','查看定制型案例',UserIsInRole('A04',$adminRole)),
			new PowerItem('A05','查看套餐型案例',UserIsInRole('A05',$adminRole)),
			new PowerItem('A06','查看入门型案例',UserIsInRole('A06',$adminRole)),
			new PowerItem('A2' , '添加客户',UserIsInRole('A2',$adminRole)),
			new PowerItem('A22' , '系统用户管理',UserIsInRole('A22',$adminRole)),
			new PowerItem('A3' , '修改客户',UserIsInRole('A3',$adminRole)),
			new PowerItem('A5' , '锁定/解锁客户',UserIsInRole('A5',$adminRole)),
			new PowerItem('A14' , '数据备份/还原',UserIsInRole('A14',$adminRole)),
			new PowerItem('A8' , '客户日志查看',UserIsInRole('A8',$adminRole)),
			new PowerItem('A80','客户后台日志',UserIsInRole('A80',$adminRole)),
			new PowerItem('A6' , '域名指向/备案',UserIsInRole('A6',$adminRole)),
			new PowerItem('A7' , '客户分配',UserIsInRole('A7',$adminRole)),
			new PowerItem('A9' , '页面跳转',UserIsInRole('A9',$adminRole)),
			new PowerItem('A10' , '项目状态',UserIsInRole('A10',$adminRole)),
			new PowerItem('A11' , '添加项目进度信息',UserIsInRole('A11',$adminRole)),
			new PowerItem('A12' , '查看项目进度信息',UserIsInRole('A12',$adminRole)),
			new PowerItem('A13' , '查看项目反馈信息',UserIsInRole('A13',$adminRole)),
			new PowerItem('C1' , '添加语言及模板',UserIsInRole('C1',$adminRole)),
			new PowerItem('C2' , '修改语言及模板',UserIsInRole('C2',$adminRole)),
			new PowerItem('C3' , '删除语言及模板',UserIsInRole('C3',$adminRole)),
			new PowerItem('C4' , '导入资料',UserIsInRole('C4',$adminRole)),
			new PowerItem('A15' , '资料人员分配',UserIsInRole('A15',$adminRole)),
			new PowerItem('A16' , '统计',UserIsInRole('A16',$adminRole)),
			new PowerItem('A17', '修改客户名称', UserIsInRole('A17', $adminRole))
		)),
	array("模板管理",
		array(
			new PowerItem('B0' , '查看全部模板',UserIsInRole('B0',$adminRole)),
			new PowerItem('B1' , '查看个人管理的模板',UserIsInRole('B1',$adminRole)),
			new PowerItem('B2' , '添加模板',UserIsInRole('B2',$adminRole)),
			new PowerItem('B3' , '修改模板',UserIsInRole('B3',$adminRole)),
			new PowerItem('B6' , '单页修改',UserIsInRole('B6',$adminRole)),
			new PowerItem('B5' , '锁定/解锁模板',UserIsInRole('B5',$adminRole)),
			new PowerItem('B7' , '模板详细',UserIsInRole('B7',$adminRole)),
			new PowerItem('B8' , '模板分配',UserIsInRole('B8',$adminRole))
		)),
	array("数据字典管理",
		array(
			new PowerItem('P0' , '查看数据字典',UserIsInRole('P0',$adminRole)),
			new PowerItem('P1' , '添加数据字典',UserIsInRole('P1',$adminRole)),
			new PowerItem('P2' , '修改数据字典',UserIsInRole('P2',$adminRole)),
			new PowerItem('P3' , '显示/隐藏数据字典',UserIsInRole('P3',$adminRole))
		)),
	array("老网站密码管理",
		array(new PowerItem('U0' , '老网站密码查询',UserIsInRole('U0',$adminRole)))),
	array("免费模板管理",
		array(new PowerItem('T0' , '免费模板查看',UserIsInRole('T0',$adminRole)))),
	array("功能模块管理",
		array(new PowerItem('X0' , '功能模块管理',UserIsInRole('X0',$adminRole)))),
	array("用户密码设置",
		array(new PowerItem('Z0' , '用户密码设置',UserIsInRole('Z0',$adminRole)))),
	array("DW模板下载",
		array(new PowerItem('Z1' , 'DW模板下载',UserIsInRole('Z1',$adminRole))))
);
?>
